'use client'

// Document Preview Component for regatta.club Document Generator
import { useState } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Download, FileText, Copy, Check } from 'lucide-react'
import { racingRules } from '@/lib/racing-rules'
import { toast } from 'sonner'

interface DocumentPreviewProps {
  eventData: Record<string, string>
  selectedRules: string[]
  modifiedRules: Record<string, string>
  customFields: Record<string, string>
}

export function DocumentPreview({
  eventData,
  selectedRules,
  modifiedRules,
  customFields,
}: DocumentPreviewProps) {
  const [copiedDoc, setCopiedDoc] = useState<string | null>(null)

  const generateNoticeOfRace = () => {
    const norRules = racingRules.filter(
      (rule) => selectedRules.includes(rule.id) && (rule.section === 'nor' || rule.section === 'both')
    )

    let markdown = `# ${eventData.title || 'EVENT NAME'}\n\n`
    markdown += `## Notice of Race\n\n`
    
    if (eventData.dates) {
      markdown += `**Date:** ${eventData.dates}\n\n`
    }
    
    if (eventData.organizingAuthority) {
      markdown += `**Organizing Authority:** ${eventData.organizingAuthority}\n\n`
    }

    markdown += `---\n\n`

    // 1. RULES
    markdown += `## 1. RULES\n\n`
    markdown += `The regatta will be governed by the rules as defined in The Racing Rules of Sailing 2025-2028.\n\n`

    if (norRules.length > 0) {
      norRules.forEach((rule) => {
        const text = modifiedRules[rule.id] || rule.defaultText
        markdown += `${text}\n\n`
      })
    }

    // 2. ELIGIBILITY
    markdown += `## 2. ELIGIBILITY\n\n`
    markdown += `Open to all boats that comply with the requirements specified herein.\n\n`

    // 3. CLASSES/DIVISIONS
    if (eventData.classes) {
      markdown += `## 3. CLASSES AND DIVISIONS\n\n`
      markdown += `${eventData.classes}\n\n`
    }

    // 4. ENTRY AND FEES
    markdown += `## 4. ENTRY AND FEES\n\n`
    if (eventData.registrationLink) {
      markdown += `Entries can be submitted at: ${eventData.registrationLink}\n\n`
    }
    if (eventData.entryFee) {
      markdown += `**Entry Fee:** ${eventData.entryFee}\n\n`
    }

    // 5. SCHEDULE
    markdown += `## 5. SCHEDULE\n\n`
    if (eventData.dates) {
      markdown += `**Race Date:** ${eventData.dates}\n\n`
    }

    // 6. SAILING INSTRUCTIONS
    markdown += `## 6. SAILING INSTRUCTIONS\n\n`
    markdown += `Sailing instructions will be available online and at the race office.\n\n`

    // 7. VENUE
    if (eventData.venue || eventData.racingArea) {
      markdown += `## 7. VENUE\n\n`
      if (eventData.venue) {
        markdown += `**Location:** ${eventData.venue}\n\n`
      }
      if (eventData.racingArea) {
        markdown += `**Racing Area:** ${eventData.racingArea}\n\n`
      }
      if (eventData.courseLength) {
        markdown += `**Course Length:** ${eventData.courseLength}\n\n`
      }
    }

    // 8. SCORING
    if (eventData.scoringSystem) {
      markdown += `## 8. SCORING\n\n`
      markdown += `${eventData.scoringSystem}\n\n`
    }

    // 9. PRIZES
    if (eventData.awardsDateTime) {
      markdown += `## 9. PRIZES\n\n`
      markdown += `Awards will be presented at ${eventData.awardsDateTime}.\n\n`
    }

    // Custom Fields
    Object.entries(customFields).forEach(([fieldName, fieldValue]) => {
      if (fieldValue.trim()) {
        markdown += `## ${fieldName.toUpperCase()}\n\n`
        markdown += `${fieldValue}\n\n`
      }
    })

    // CONTACT
    markdown += `## CONTACT INFORMATION\n\n`
    if (eventData.contactName) {
      markdown += `**Name:** ${eventData.contactName}\n\n`
    }
    if (eventData.contactEmail) {
      markdown += `**Email:** ${eventData.contactEmail}\n\n`
    }
    if (eventData.contactPhone) {
      markdown += `**Phone:** ${eventData.contactPhone}\n\n`
    }

    markdown += `---\n\n`
    markdown += `*This document is generated by regatta.club Document Generator*\n`

    return markdown
  }

  const generateSailingInstructions = () => {
    const siRules = racingRules.filter(
      (rule) => selectedRules.includes(rule.id) && (rule.section === 'si' || rule.section === 'both')
    )

    let markdown = `# ${eventData.title || 'EVENT NAME'}\n\n`
    markdown += `## Sailing Instructions\n\n`
    
    if (eventData.dates) {
      markdown += `**Date:** ${eventData.dates}\n\n`
    }

    markdown += `---\n\n`

    // 1. RULES
    markdown += `## 1. RULES\n\n`
    markdown += `### 1.1 GOVERNANCE\n\n`
    markdown += `Races will be governed by the Racing Rules of Sailing 2025-2028`
    if (eventData.organizingAuthority) {
      markdown += ` and ${eventData.organizingAuthority} Sailing Instructions`
    }
    markdown += `.\n\n`

    if (siRules.length > 0) {
      siRules.forEach((rule) => {
        const text = modifiedRules[rule.id] || rule.defaultText
        markdown += `${text}\n\n`
      })
    }

    // 2. NOTICES TO COMPETITORS
    markdown += `## 2. NOTICES TO COMPETITORS\n\n`
    markdown += `Notices to competitors will be posted on the official notice board.\n\n`

    // 3. CHANGES TO SAILING INSTRUCTIONS
    markdown += `## 3. CHANGES TO SAILING INSTRUCTIONS\n\n`
    markdown += `Any change to the sailing instructions will be posted before the warning signal of the race to which it applies.\n\n`

    // 4. SIGNALS
    if (eventData.vhfChannel) {
      markdown += `## 4. SIGNALS\n\n`
      markdown += `Race signals will be made on VHF ${eventData.vhfChannel}.\n\n`
    }

    // 5. SCHEDULE
    markdown += `## 5. SCHEDULE\n\n`
    if (eventData.dates) {
      markdown += `**Race Date:** ${eventData.dates}\n\n`
    }

    // 6. RACING AREA
    if (eventData.racingArea) {
      markdown += `## 6. RACING AREA\n\n`
      markdown += `${eventData.racingArea}\n\n`
    }

    // 7. THE COURSES
    if (eventData.courseLength) {
      markdown += `## 7. THE COURSES\n\n`
      markdown += `Course length: ${eventData.courseLength}\n\n`
      markdown += `Course details will be provided separately.\n\n`
    }

    // 8. MARKS
    markdown += `## 8. MARKS\n\n`
    markdown += `Marks will be as specified in the course sheet.\n\n`

    // 9. THE START
    markdown += `## 9. THE START\n\n`
    markdown += `Races will be started using RRS 26.\n\n`

    // 10. THE FINISH
    markdown += `## 10. THE FINISH\n\n`
    markdown += `The finishing line will be between the staff displaying a blue flag on the committee boat and a nearby mark.\n\n`

    // 11. TIME LIMITS
    if (eventData.timeLimit) {
      markdown += `## 11. TIME LIMITS\n\n`
      markdown += `**Time Limit:** ${eventData.timeLimit}\n\n`
    }

    // 12. PROTESTS AND REQUESTS FOR REDRESS
    markdown += `## 12. PROTESTS AND REQUESTS FOR REDRESS\n\n`
    markdown += `Protests shall be submitted in accordance with RRS 61.\n\n`

    // 13. SCORING
    if (eventData.scoringSystem) {
      markdown += `## 13. SCORING\n\n`
      markdown += `${eventData.scoringSystem}\n\n`
    }

    // 14. SAFETY
    markdown += `## 14. SAFETY\n\n`
    markdown += `A boat that retires from a race shall notify the race committee as soon as possible.\n\n`

    // Custom Fields
    Object.entries(customFields).forEach(([fieldName, fieldValue]) => {
      if (fieldValue.trim()) {
        markdown += `## ${fieldName.toUpperCase()}\n\n`
        markdown += `${fieldValue}\n\n`
      }
    })

    // AWARDS
    if (eventData.awardsDateTime) {
      markdown += `## AWARDS\n\n`
      markdown += `Awards will be presented at ${eventData.awardsDateTime}.\n\n`
    }

    markdown += `---\n\n`
    markdown += `*This document is generated by regatta.club Document Generator*\n`

    return markdown
  }

  const handleDownload = (type: 'nor' | 'si') => {
    const markdown = type === 'nor' ? generateNoticeOfRace() : generateSailingInstructions()
    const blob = new Blob([markdown], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${eventData.title || 'document'}_${type === 'nor' ? 'NoR' : 'SI'}.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    toast.success(`${type === 'nor' ? 'Notice of Race' : 'Sailing Instructions'} downloaded`)
  }

  const handleCopy = async (type: 'nor' | 'si') => {
    const markdown = type === 'nor' ? generateNoticeOfRace() : generateSailingInstructions()
    await navigator.clipboard.writeText(markdown)
    setCopiedDoc(type)
    toast.success('Copied to clipboard')
    setTimeout(() => setCopiedDoc(null), 2000)
  }

  const norMarkdown = generateNoticeOfRace()
  const siMarkdown = generateSailingInstructions()

  return (
    <div className="grid gap-6 lg:grid-cols-2">
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="flex items-center gap-2">
                <FileText className="w-5 h-5" />
                Notice of Race
              </CardTitle>
              <CardDescription>Preview and export your NoR document</CardDescription>
            </div>
            <div className="flex gap-2">
              <Button
                variant="outline"
                size="sm"
                onClick={() => handleCopy('nor')}
              >
                {copiedDoc === 'nor' ? (
                  <Check className="w-4 h-4" />
                ) : (
                  <Copy className="w-4 h-4" />
                )}
              </Button>
              <Button onClick={() => handleDownload('nor')} size="sm">
                <Download className="w-4 h-4 mr-2" />
                Download
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <ScrollArea className="h-[600px] w-full rounded-md border p-4">
            <pre id="preview-nor" className="text-sm whitespace-pre-wrap font-mono">
              {norMarkdown}
            </pre>
          </ScrollArea>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="flex items-center gap-2">
                <FileText className="w-5 h-5" />
                Sailing Instructions
              </CardTitle>
              <CardDescription>Preview and export your SI document</CardDescription>
            </div>
            <div className="flex gap-2">
              <Button
                variant="outline"
                size="sm"
                onClick={() => handleCopy('si')}
              >
                {copiedDoc === 'si' ? (
                  <Check className="w-4 h-4" />
                ) : (
                  <Copy className="w-4 h-4" />
                )}
              </Button>
              <Button onClick={() => handleDownload('si')} size="sm">
                <Download className="w-4 h-4 mr-2" />
                Download
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <ScrollArea className="h-[600px] w-full rounded-md border p-4">
            <pre id="preview-si" className="text-sm whitespace-pre-wrap font-mono">
              {siMarkdown}
            </pre>
          </ScrollArea>
        </CardContent>
      </Card>
    </div>
  )
}
